- id: renovate-config-validator
  name: renovate-config-validator
  description: Validate Renovate config
  language: node
  additional_dependencies: [renovate@35.24.5]
  entry: renovate-config-validator
  files: '(^|/).?renovate(?:rc)?(?:\.json5?)?$'
