name: build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version-file: .python-version
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pre-commit
        run: >-
          pre-commit try-repo --all-files
          --ref="${GITHUB_SHA}"
          "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"

  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Get Renovate version
        id: get-renovate-version
        uses: mikefarah/yq@1c3d55106075bd37df197b4bc03cb4a413fdb903 # v4.40.4
        with:
          cmd: >-
            yq eval
            '.[]|select(.id=="renovate-config-validator")|.additional_dependencies[0]|split("@").[1]'
            .pre-commit-hooks.yaml

      - name: Create release
        run: |
          if ! gh release view "${TAG}" >/dev/null; then
            gh release create "${TAG}" \
              --notes "See https://github.com/renovatebot/renovate/releases/tag/${TAG} for more changes" \
              --target "${TARGET}" \
              --title "${TAG}"
          else
            echo 'release already exists'
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.get-renovate-version.outputs.result }}
          TARGET: ${{ github.sha }}
