name: build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Set up Python
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version-file: .python-version
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pre-commit
        run: >-
          pre-commit try-repo --all-files
          --ref="${GITHUB_SHA}"
          "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"

  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Get Renovate version
        id: get-renovate-version
        uses: mikefarah/yq@4ee4b09e12ab319a48c6f7eae026030081cb0cc3 # v4.32.2
        with:
          cmd: >-
            yq eval
            '.[]|select(.id=="renovate-config-validator")|.additional_dependencies[0]|split("@").[1]'
            .pre-commit-hooks.yaml

      - name: Create release
        run: |
          if ! gh release view "${TAG}" >/dev/null; then
            gh release create "${TAG}" \
              --notes "See https://github.com/renovatebot/renovate/releases/tag/${TAG} for more changes" \
              --target "${TARGET}" \
              --title "${TAG}"
          else
            echo 'release already exists'
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.get-renovate-version.outputs.result }}
          TARGET: ${{ github.sha }}
