name: build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version-file: .python-version
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pre-commit
        run: >-
          pre-commit try-repo --all-files
          --ref="${GITHUB_SHA}"
          "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"

  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Get Renovate version
        id: get-renovate-version
        uses: mikefarah/yq@557dcb87b8efe786f89a12c09e9046b4753ab72e # v4.44.1
        with:
          cmd: >-
            yq eval
            '.[]|select(.id=="renovate-config-validator")|.additional_dependencies[0]|split("@").[1]'
            .pre-commit-hooks.yaml

      - name: Create release
        run: |
          if ! gh release view "${TAG}" >/dev/null; then
            gh release create "${TAG}" \
              --notes "See https://github.com/renovatebot/renovate/releases/tag/${TAG} for more changes" \
              --target "${TARGET}" \
              --title "${TAG}"
          else
            echo 'release already exists'
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.get-renovate-version.outputs.result }}
          TARGET: ${{ github.sha }}
