name: tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
        with:
          fetch-depth: 0 # all tags

      - name: Get Renovate version
        id: get-renovate-version
        uses: mikefarah/yq@3924ed8a35a3edd80732ace69d79624f4fa49d2d # tag=v4.22.1
        with:
          cmd: >-
            yq eval
            '.[]|select(.id=="renovate-config-validator")|.additional_dependencies[0]|split("@").[1]'
            .pre-commit-hooks.yaml

      - name: Create tag
        run: |
          TAG=${{ steps.get-renovate-version.outputs.result }}
          if ! git show-ref --tags "${TAG}" --quiet; then
            git tag "${TAG}" && git push origin "${TAG}"
          fi

  test:
    needs: [tag]
    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@7f80679172b057fc5e90d70d197929d454754a5a # renovate: tag=v2.3.2

      - name: Run pre-commit
        uses: pre-commit/action@9b88afc9cd57fd75b655d5c71bd38146d07135fe # renovate: tag=v2.0.3
        with:
          extra_args: --all-files
